//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacione
    {
        public int IdReservaciones { get; set; }
        public int IdCliente { get; set; }
        public int IdMesa { get; set; }
        public int IdMenu { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaReservacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
