//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    
    public partial class RDEntities : DbContext
    {
        public RDEntities()
            : base("name=RDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<Reservacione> Reservaciones { get; set; }
    
        public virtual int PA_delCliente(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delCliente", idClienteParameter);
        }
    
        public virtual int PA_delMenu(Nullable<int> idMenu)
        {
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("IdMenu", idMenu) :
                new ObjectParameter("IdMenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delMenu", idMenuParameter);
        }
    
        public virtual int PA_delMesa(Nullable<int> idMesa)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("IdMesa", idMesa) :
                new ObjectParameter("IdMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delMesa", idMesaParameter);
        }
    
        public virtual int PA_delReservacion(Nullable<int> idReservaciones)
        {
            var idReservacionesParameter = idReservaciones.HasValue ?
                new ObjectParameter("IdReservaciones", idReservaciones) :
                new ObjectParameter("IdReservaciones", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delReservacion", idReservacionesParameter);
        }
    
        public virtual int PA_insCliente(string nombre, string apellido, string telefono, string correo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insCliente", nombreParameter, apellidoParameter, telefonoParameter, correoParameter);
        }
    
        public virtual int PA_insMenu(string descripcion, Nullable<decimal> precio)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insMenu", descripcionParameter, precioParameter);
        }
    
        public virtual int PA_insMesa(Nullable<int> numeroMesa, Nullable<int> capacidad, string estado)
        {
            var numeroMesaParameter = numeroMesa.HasValue ?
                new ObjectParameter("NumeroMesa", numeroMesa) :
                new ObjectParameter("NumeroMesa", typeof(int));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insMesa", numeroMesaParameter, capacidadParameter, estadoParameter);
        }
    
        public virtual int PA_insReservacion(Nullable<int> idCliente, Nullable<int> idMesa, Nullable<int> idMenu, Nullable<int> cantidad, Nullable<System.DateTime> fechaReservacion)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("IdMesa", idMesa) :
                new ObjectParameter("IdMesa", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("IdMenu", idMenu) :
                new ObjectParameter("IdMenu", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var fechaReservacionParameter = fechaReservacion.HasValue ?
                new ObjectParameter("FechaReservacion", fechaReservacion) :
                new ObjectParameter("FechaReservacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insReservacion", idClienteParameter, idMesaParameter, idMenuParameter, cantidadParameter, fechaReservacionParameter);
        }
    
        public virtual int PA_modCliente(Nullable<int> idCliente, string nombre, string apellido, string telefono, string correo)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modCliente", idClienteParameter, nombreParameter, apellidoParameter, telefonoParameter, correoParameter);
        }
    
        public virtual int PA_modMenu(Nullable<int> idMenu, string descripcion, Nullable<decimal> precio)
        {
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("IdMenu", idMenu) :
                new ObjectParameter("IdMenu", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modMenu", idMenuParameter, descripcionParameter, precioParameter);
        }
    
        public virtual int PA_modMesa(Nullable<int> idMesa, Nullable<int> numeroMesa, Nullable<int> capacidad, string estado)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("IdMesa", idMesa) :
                new ObjectParameter("IdMesa", typeof(int));
    
            var numeroMesaParameter = numeroMesa.HasValue ?
                new ObjectParameter("NumeroMesa", numeroMesa) :
                new ObjectParameter("NumeroMesa", typeof(int));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modMesa", idMesaParameter, numeroMesaParameter, capacidadParameter, estadoParameter);
        }
    
        public virtual int PA_modReservacion(Nullable<int> idReservaciones, Nullable<int> idCliente, Nullable<int> idMesa, Nullable<int> idMenu, Nullable<int> cantidad, Nullable<System.DateTime> fechaReservacion)
        {
            var idReservacionesParameter = idReservaciones.HasValue ?
                new ObjectParameter("IdReservaciones", idReservaciones) :
                new ObjectParameter("IdReservaciones", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("IdMesa", idMesa) :
                new ObjectParameter("IdMesa", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("IdMenu", idMenu) :
                new ObjectParameter("IdMenu", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var fechaReservacionParameter = fechaReservacion.HasValue ?
                new ObjectParameter("FechaReservacion", fechaReservacion) :
                new ObjectParameter("FechaReservacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modReservacion", idReservacionesParameter, idClienteParameter, idMesaParameter, idMenuParameter, cantidadParameter, fechaReservacionParameter);
        }
    
        public virtual ObjectResult<PA_recClientes_Result> PA_recClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recClientes_Result>("PA_recClientes");
        }
    
        public virtual ObjectResult<PA_recClienteXId_Result> PA_recClienteXId(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recClienteXId_Result>("PA_recClienteXId", idClienteParameter);
        }
    
        public virtual ObjectResult<PA_recMenu_Result> PA_recMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMenu_Result>("PA_recMenu");
        }
    
        public virtual ObjectResult<PA_recMenuXId_Result> PA_recMenuXId(Nullable<int> idMenu)
        {
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("IdMenu", idMenu) :
                new ObjectParameter("IdMenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMenuXId_Result>("PA_recMenuXId", idMenuParameter);
        }
    
        public virtual ObjectResult<PA_recMesas_Result> PA_recMesas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMesas_Result>("PA_recMesas");
        }
    
        public virtual ObjectResult<PA_recMesaXId_Result> PA_recMesaXId(Nullable<int> idMesa)
        {
            var idMesaParameter = idMesa.HasValue ?
                new ObjectParameter("IdMesa", idMesa) :
                new ObjectParameter("IdMesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMesaXId_Result>("PA_recMesaXId", idMesaParameter);
        }
    
        public virtual ObjectResult<PA_recReservaciones_Result> PA_recReservaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recReservaciones_Result>("PA_recReservaciones");
        }
    
        public virtual ObjectResult<PA_recReservacionXId_Result> PA_recReservacionXId(Nullable<int> idReservaciones)
        {
            var idReservacionesParameter = idReservaciones.HasValue ?
                new ObjectParameter("IdReservaciones", idReservaciones) :
                new ObjectParameter("IdReservaciones", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recReservacionXId_Result>("PA_recReservacionXId", idReservacionesParameter);
        }
    }
}
